services:
  _defaults:
    autowire: true
    autoconfigure: true

  Tourze\JsonRPCProcedureCollectBundle\Service\:
    resource: '../../Service/'
  Tourze\JsonRPCProcedureCollectBundle\Procedure\:
    resource: '../../Procedure/'
